#zero division error
# def compute_division():
#     try:
#         result = 5 / 0
#         return result
#     except ZeroDivisionError:#exception type
#         print("Error: Division by zero is not allowed.")
#         return None

# # Call the function
# result = compute_division()

# # Check if the result is None (indicating an error)
# if result is not None:
#     print("Result:", result)


#The try and except blocks in Python are used for error handling
#try:
    # Code that might raise an exception
    # ...
#except ExceptionType as e:
    # Code to handle the exception
#If no exception occurs, the code inside the except block is skipped
#Using try and except allows you to gracefully handle errors and prevent your program from crashing when unexpected issues arise
